### ISSUE TITLE
Twitter Bot: Posts Tweets:

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#325]
### Description

Posts tweets:

Response:
[NAME]: [TIME] (#[PLACE])
[VIDEO]

Daily:
New daily puzzle! [LINK]

**Comment by alhardwarehyde** [comment]
@camdan-me do you want to take a pass at the copy?

**Comment by camdan-me** [comment]
I would just do something like this

Response:
`[NAME]`: `[TIME]` (#`[PLACE]`)
`[VIDEO]`

Daily:
New daily puzzle! `[LINK]`

**Comment by karamassie** [comment]
agreed. let's try this and get feedback asap

**Comment by grymmy** [comment]
I don't think tweeting with the place (#1, #2) on the leaderboard makes much sense as it can very quickly become incorrect due to other submissions.  I think the time, level (puzzle) name, character count, and video should be contained in the msg - we could also put a quick link to the relevant leaderboard where realtime results can be displayed too...

As it stands right now, here is the copy we currently utilize for auto-responses:

**Use case #1**: Submission accepted and scored with valid time and adding user to the leaderboard
**Copy**:  Good job, you made it on the leaderboard for %s with a time of %f and a charCount of %d.  Check out this video of your run!" % (score_data["level"], score_data["time"], score_data["charCount"], score_data["gameplay"])

**Use case #2**: An unknown error occurs when responding to what looks at first glance to be a valid submission
**Copy**:  Sorry, I encountered an error scoring that submission :(

**Use case #3**: Submission looked valid but duplicate entry already existed in the leaderboards
**Copy**:  Sorry, someone already submitted that solution to the leaderboards!

**Use case #4**: Submission looked valid but scoring times out (>30s)
**Copy**: Sorry, that submission takes longer than 30 seconds to evaluate, and thus is disqualified :(

**Use case #5**: #sinerider was in the Tweet, but the format of the tweet doesn't appear to be a submission.
**Copy**: N/A, bot does not respond.

@karamassie @developedbytoby @alhardwarehyde @camdan-me what do you think?

**Comment by developedbytoby** [comment]
I agree; I think the only situation where it could work would be if we were to say something like "As of [time], you're in 2nd place!" Or something along the lines of that. Even then, that would still be a bit janky.

**Comment by developedbytoby** [comment]
The current response to an answer being resubmitted is pretty confusing; the current wording: "Sorry, someone already submitted that solution to the leaderboards!", should instead be replaced with something like "try a different answer!"

**Comment by bellesea** [comment]
hiiii this looks awesome! some suggestions:

Use case 1: Submission accepted and scored with valid time and adding user to the leaderboard
Copy: Good job, you made it on the leaderboard for %s with a time of %f and a charCount of %d. Check out this video of your run: %s" % (score_data["level"], score_data["time"], score_data["charCount"], score_data["gameplay"])
Alt Copy: Copy: Good job, you made it on the leaderboard for %s with a time of %f and an expression length of %d. Check out this video of your run: %s" % (score_data["level"], score_data["time"], score_data["charCount"], score_data["gameplay"])
Reason: charCount is confusing, chatted with graham about this yesterday

Use case 3: Submission looked valid but duplicate entry already existed in the leaderboards
Copy: Sorry, someone already submitted that solution to the leaderboards!
Alt Copy: Sorry, someone already submitted that solution to the leaderboards — try again with a different answer!
(Agree w/ Toby's suggestion)

Use case 4: Submission looked valid but scoring times out (>30s)
Copy: Sorry, that submission takes longer than 30 seconds to evaluate so we had to disqualify it :( Try again with a different solution!

Use case 5: #sinerider was in the Tweet, but the format of the tweet doesn't appear to be a submission.
Copy: N/A, bot does not respond.

Overall, i think these would work but would be even better if it had Scrappy's personality... 

eg. Right on! You made it to %s's leaderboard with a time of %f (vroom vroom!) Check out your magnificent run:

**Comment by karamassie** [comment]
@developedbytoby  you good to implement belle's suggested copy?

**Comment by developedbytoby** [comment]
Yep! Working on it now!

**Comment by GalaxyGamingBoy** [comment]
@bellesea I will also implement this in the reddit bot!

**Comment by grymmy** [comment]
@GalaxyGamingBoy @developedbytoby I like @bellesea 's ideas here, but strongly think we should use some sort of shared resource across both the reddit and twitter bots such that we can update this copy across both without touching lots of individual lines of code.  Can we use something like a yaml config to share this across both, using some sort of substitutable placeholder for values that need to be filled in?

**Comment by grymmy** [comment]
@developedbytoby I believe this issue can be closed even though we don't share the yaml resource across both reddit & twitter - please do so if the current flavor text equals what was communicated here

**Comment by developedbytoby** [comment]
Everything looks good!
