### ISSUE TITLE
Replace Music in Game with Final Versions

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#393]
### Description

What it says above

**Comment by josephdong1000** [comment]
Nope, we still gotta do this. One of the devs was talking about compressing
the files. I'm also not sure of which file in the repo is what, but I think

I also wanna know, were the volume levels adjusted in-game on any of the
tracks? Because for this final version, all the volume levels shouldn't be
adjusted before they get played, since I went through each track and
balanced the volume levels. Except for the player's volume slide, that can
adjust volume of course.
ᐧ

**Comment by josephdong1000** [comment]
The volume-difference issue aside, I think it's easier for me to upload each of the audios individually, since I know what my files are called what

**Comment by karamassie** [comment]
@josephdong1000 can you work with claire to get this done then?

**Comment by josephdong1000** [comment]
I can do that. What does the timeframe look like, tonight? I'm rather busy but if it's necessary I can do that.

**Comment by karamassie** [comment]
early next week is great!!

**Comment by polytroper** [comment]
done
