### ISSUE TITLE
Twitter bot's responses are hidden (see image)

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#499]
### Description

<img width="377" alt="Screen Shot 2023-05-05 at 6 46 43 PM" src="https://user-images.githubusercontent.com/99233707/236581240-9c30a7d1-1b9d-4454-9a30-e66ccab07462.png">

**Comment by grymmy** [comment]
I have marked this issue as potentially hard to fix, and potentially low priority.  To my knowledge, there is no exact criteria that Twitter shares that tells you exactly how to avoid being flagged for potentially offensive/spammy content.  If someone is aware of a specific change we can make (other than just waiting for their systems to not flag us due to continued normal use & interactions on twitter), please inform me.

**Comment by karamassie** [comment]
@polytroper do you know some magic here?

**Comment by grymmy** [comment]
@karamassie be aware, I am closing this as WONTFIX - based on my understanding, continued interaction from users as well as the fact that we are posting media content now makes me believe we will be flagged re: this less over time naturally.

**Comment by grymmy** [comment]
@polytroper also plz be aware ^^^
