### ISSUE TITLE
Twitter -- support 1600tweets / day

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#524]
### Description

Using Multiple Bots to Support 1600 Tweets/Day

**Comment by grymmy** [comment]
I have confirmed that we are NOT capped at 100 tweets/day.  It is extremely likely that we are being capped at the daily app-scope limit (1667/day).  

However, I ran a test and saw that we were indeed being rate limited after 300 tweets.  This is explained in a comment in the [twitter documentation](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/introduction):

![Image](https://github.com/hackclub/sinerider/assets/43505167/fb75bc34-192a-4576-a320-5689e7271dd1)

I can also see that the header coming back from failed (due to rate limiting) responses has the following header:

`{'date': 'Wed, 10 May 2023 19:37:14 UTC', 'perf': '7626143928', 'server': 'tsa_b', 'set-cookie': 'guest_id_marketing=v1%3A168374743490593419; Max-Age=63072000; Expires=Fri, 09 May 2025 19:37:14 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None, guest_id_ads=v1%3A168374743490593419; Max-Age=63072000; Expires=Fri, 09 May 2025 19:37:14 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None, personalization_id="v1_PfnnOJX5UqB5bsUVpGKnqQ=="; Max-Age=63072000; Expires=Fri, 09 May 2025 19:37:14 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None, guest_id=v1%3A168374743490593419; Max-Age=63072000; Expires=Fri, 09 May 2025 19:37:14 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None', 'api-version': '2.62', 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache, no-store, max-age=0', 'content-length': '94', 'x-access-level': 'read-write', 'x-frame-options': 'SAMEORIGIN', 'content-encoding': 'gzip', 'x-transaction-id': '06dfe245f6872a73', 'x-xss-protection': '0', 'x-rate-limit-limit': '40000', 'x-rate-limit-reset': '1683748334', 'content-disposition': 'attachment; filename=json.json', 'x-content-type-options': 'nosniff', 'x-rate-limit-remaining': '39999', 'strict-transport-security': 'max-age=631138519', 'x-response-time': '73', 'x-connection-hash': '43d434a46aa1c73a5a7239ff5bf4ccad6c610e684ce4769373e1dae05aa96a1c'}`

Based on this data and some napkin math that @maxwofford and I did, the plan is the following:

1) We will provision two accounts with Basic twitter access ($100/mo) (already done)
2) We will create two applications per account (total of 4)
3) Make a code modification to the twitter bot to use this pool of 4 different credentials in a round-robin manner

This should result in the following load-handling characteristics:

1) We will support a theoretic maximum of 1200 tweet responses over the course of a 3 hour period.  Any more than that will result in our getting rate limited.
2) We will support a theoretic maximum of 6668 tweet responses over the course of a day.  Any more than that will result in our getting rate limited.
3) We will support a theoretic maximum of 200k tweet responses over the course of a month.  Any more than that will result in our getting rate limited.

**Comment by grymmy** [comment]
An adjustment to the numbers above - in setting up the bot applications, it appears as though the "two apps" you get per account are not equal, but instead providing one production app and one development app.

Given this, my best guess is our theoretic maximums are half of the stated values above (600/3hr, 3300/day, 100k/mo) with our two accounts.
