### ISSUE TITLE
Work in progress: sinerider-scoring - support at minimum 20 RPM

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#540]
### Description

what it says above

**Comment by grymmy** [comment]
the sinerider-scoring service should, through vertical and/or horizontal scaling, support 20RPM

**Comment by grymmy** [comment]
we should look into the following:

1. adding a load balancer on DO
2. identify the vertical scale of the machine instance type we want to upgrade to (more cpus, SSD disk)
3. (optional) improve our deployment process if possible (dockerization/machine images/scripts if need be)
4. provision new instances behind load balancer
5. perform scoring load test / collect perf numbers

**Comment by JosiasAurel** [comment]
Could get 20 concurrent requests locally using browserless. 
On DO I couldn't get pass 10 and I think it's due to hardware limits there. I think it's ffmpeg that overflows ram there

So our best bet is browserless and we could get even more.

**Comment by grymmy** [comment]
Assigned myself this issue alongside Josias.  Progress thus far:

1. Provisioned 3 new DO droplets the same size as our original scoring-service instance.
2. Added a load balancer and configured it to point at the new cluster.

This afternoon I will be implementing a script to efficiently deploy to these machines as manually updating the code (like we've been doing w/ the one instance) will waste time & run us into errors.

**Comment by grymmy** [comment]
Update - we have now deployed the sinerider-scoring service as an App on DO.  Instance sizes are 1gb RAM 1VCPU (xsmall).  Using our load-testing script we observe these results using the following settings:

**Settings**:
- 10 instances in cluster
- Load-testing [script](https://github.com/grymmy/sinerider-scoring/blob/main/script/hailstorm.py): `python3 hailstorm.py https://sinerider-scoring-od9e5.ondigitalocean.app -d -r 5 -n 100 -t 32` (5 req/sec, 100 requests, 32 max parallel requests simultaneously, rate-limited requests are requeued)
- sinerider-scoring ENV vars: `RATE_LIMIT_MAX_REQUESTS=1, RATE_LIMIT_WINDOW_MS=15000, TICK_RATE=120, DRAW_MODULO=3`

**Results**: 21.59 RPM

Results from this test (which did test accuracy as well as perf) did show a small percentage of failed (incorrect) responses.  These problems are tracked by issue #534.
Results from this test do not properly simulate the load expected from the bot services.  At the time of this writing, the Twitter bot (nor the Reddit bot) send parallel requests to the sinerider-scoring service, and this needs to change to leverage the increased throughput in this service.  This issue is tracked by #565.
