### ISSUE TITLE
Proper victory screen

### ISSUE THREAD

**Issue by karamassie** [hackclub/sinerider#64]
We need a proper victory screen that shows the time a solution required to complete and the length of the function. These are the two "scores" for a sinerider solution.

**Comment by alhardwarehyde** [comment]
This also came up in HQ Feedback and should be addressed.

**Comment by alhardwarehyde** [comment]
Tied to #211

**Comment by alhardwarehyde** [comment]
Related to #219

**Comment by cytronicoder** [comment]
I might tentatively take this after looking through all the relevant code haha

**Comment by cytronicoder** [comment]
> @cytronicoder just checking in, is this something you can take on? (also reach out to @polytroper if you want to get involved but need help getting started).
> 
> Thank you!!

Yes! I might need some help getting started 😄

**Comment by cytronicoder** [comment]
> @cytronicoder just checking in, is this something you can take on? (also reach out to @polytroper if you want to get involved but need help getting started).
> 
> Thank you!!

Yes! I might need some help getting started 😄

**Comment by alhardwarehyde** [comment]
@cytronicoder you're on the Hack Club Slack right? I suggest checking out #gamedev which has some resources and putting out an ask there.

**Comment by polytroper** [comment]
@cytronicoder First, make sure you are synced to main because I just made several relevant changes.

What we want is for the victory screen to display the number of characters in your solution and the time it took to run. Right now the victory screen looks like this:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/15720465/227618838-0be21684-4285-48c3-a648-1d740bd7a31e.png">

So first, add the HTML and CSS to show these things in `index.html`. Then, add them to the `ui` object in `main.js` so we can wire it all up. In `world.js` there is this function:

```
  function levelCompleted(soft = false) {
    setCompletionTime(runTime)

    if (soft) {
      nextLevel(2.5)
    } else {
      ui.victoryBar.setAttribute('hide', false)
      ui.expressionEnvelope.setAttribute('hide', true)
      ui.showAllButton.setAttribute('hide', true)
    }

    levelBubble.complete()
  }
```

In that `else` block where all the UI attributes are set, you will need to set the time/charcount for the current solution. The time is just `runTime` and the charcount is just `ui.mathField.latex().length`

**Comment by cytronicoder** [comment]
@polytroper Got it; will work on it today 🧙‍♂️

**Comment by cytronicoder** [comment]
@Omay238 I'll wrap it up today if you don't mind
Of course, if you have a pull request in the making already, let me know!

**Comment by Omay238** [comment]
Yeah, sure. I was struggling with the CSS. I haven't finished it yet.
